---
# Configuration file for https://megalinter.io/
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
PYTHON_MYPY_FILTER_REGEX_EXCLUDE: docs/
YAML_V8R_FILTER_REGEX_EXCLUDE: tests/files/
PYTHON_BANDIT_FILTER_REGEX_EXCLUDE: docs/|tests/
PYTHON_PYRIGHT_FILTER_REGEX_EXCLUDE: docs/|tests/
PYTHON_ISORT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_PYLINT_ARGUMENTS: "--disable=F0401,E0611"
MARKDOWN_MARKDOWNLINT_ARGUMENTS: "--disable MD028"
# We use custom extensions that are not supported by rstfmt
RST_RSTFMT_FILTER_REGEX_EXCLUDE: docs/source/index.rst|docs/source/design_philosophy.rst
RST_RSTCHECK_FILTER_REGEX_EXCLUDE: docs/source/index.rst|docs/source/design_philosophy.rst
RST_RST_LINT_FILTER_REGEX_EXCLUDE: docs/source/index.rst|docs/source/design_philosophy.rst|docs/source/backends.rst|docs/source/developing_backends.rst|docs/source/installing_backends.rst|docs/source/user_guide.rst
DISABLE:
  - SPELL
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
PYTHON_PYRIGHT_PRE_COMMANDS:
  - command: pip3 install .
VALIDATE_ALL_CODEBASE: true
